name: Hello World CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
          - os: windows-2019
          - os: macos-11
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }}:${{ matrix.dist_target }}"
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - run: uname
    - name: Compile it
      run: make
    - name: Run it
      run: ./Hello


