name: Hello World CI

on:
  push:
    branches: [ main ]
    tags:
      - v[0-9].[0-9]+.[0-9]+
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            executable: Hello-linux
          - os: windows-2019
            executable: Hello-win32.exe
          - os: macos-11
            executable: Hello-darwin
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }}:${{ matrix.dist_target }}"
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Compile it
      run: make
    - name: Run it
      run: ./${{ matrix.executable }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Hello
        path: ${{ matrix.executable }}
        retention-days: 5

  release:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Display downloaded
        run: ls -R
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Hello/*
