name: Hello World CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            executable: HelloLinux
          - os: windows-2019
            executable: HelloWindows.exe
          - os: macos-11
            executable: HelloDarwin
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }}:${{ matrix.dist_target }}"
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Compile it
      run: make
    - name: Run it
      run: ./${{ matrix.executable }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Hello
        path: ${{ matrix.executable }}
        retention-days: 5
